lib: [
  "_build/install/default/lib/conduit/META" {"META"}
  "_build/install/default/lib/conduit/opam" {"opam"}
  "_build/install/default/lib/conduit/conduit.cmi" {"conduit.cmi"}
  "_build/install/default/lib/conduit/conduit.cmx" {"conduit.cmx"}
  "_build/install/default/lib/conduit/conduit.cmt" {"conduit.cmt"}
  "_build/install/default/lib/conduit/conduit.cmti" {"conduit.cmti"}
  "_build/install/default/lib/conduit/conduit.mli" {"conduit.mli"}
  "_build/install/default/lib/conduit/conduit.ml" {"conduit.ml"}
  "_build/install/default/lib/conduit/conduit_trie.cmi" {"conduit_trie.cmi"}
  "_build/install/default/lib/conduit/conduit_trie.cmx" {"conduit_trie.cmx"}
  "_build/install/default/lib/conduit/conduit_trie.cmt" {"conduit_trie.cmt"}
  "_build/install/default/lib/conduit/conduit_trie.cmti"
    {"conduit_trie.cmti"}
  "_build/install/default/lib/conduit/conduit_trie.mli" {"conduit_trie.mli"}
  "_build/install/default/lib/conduit/conduit_trie.ml" {"conduit_trie.ml"}
  "_build/install/default/lib/conduit/resolver.cmi" {"resolver.cmi"}
  "_build/install/default/lib/conduit/resolver.cmx" {"resolver.cmx"}
  "_build/install/default/lib/conduit/resolver.cmt" {"resolver.cmt"}
  "_build/install/default/lib/conduit/resolver.cmti" {"resolver.cmti"}
  "_build/install/default/lib/conduit/resolver.mli" {"resolver.mli"}
  "_build/install/default/lib/conduit/resolver.ml" {"resolver.ml"}
  "_build/install/default/lib/conduit/conduit.cma" {"conduit.cma"}
  "_build/install/default/lib/conduit/conduit.cmxa" {"conduit.cmxa"}
  "_build/install/default/lib/conduit/conduit.a" {"conduit.a"}
  "_build/install/default/lib/conduit/conduit.cmxs" {"conduit.cmxs"}
  "_build/install/default/lib/conduit/conduit.dune" {"conduit.dune"}
]
doc: [
  "_build/install/default/doc/conduit/README.md"
  "_build/install/default/doc/conduit/LICENSE.md"
  "_build/install/default/doc/conduit/CHANGES.md"
]
