lib: [
  "_build/install/default/lib/magic-mime/META" {"META"}
  "_build/install/default/lib/magic-mime/opam" {"opam"}
  "_build/install/default/lib/magic-mime/magic_mime.cmi" {"magic_mime.cmi"}
  "_build/install/default/lib/magic-mime/magic_mime.cmx" {"magic_mime.cmx"}
  "_build/install/default/lib/magic-mime/magic_mime.cmt" {"magic_mime.cmt"}
  "_build/install/default/lib/magic-mime/magic_mime.cmti" {"magic_mime.cmti"}
  "_build/install/default/lib/magic-mime/magic_mime.mli" {"magic_mime.mli"}
  "_build/install/default/lib/magic-mime/magic_mime.ml" {"magic_mime.ml"}
  "_build/install/default/lib/magic-mime/mime_types.cmi" {"mime_types.cmi"}
  "_build/install/default/lib/magic-mime/mime_types.cmx" {"mime_types.cmx"}
  "_build/install/default/lib/magic-mime/mime_types.cmt" {"mime_types.cmt"}
  "_build/install/default/lib/magic-mime/mime_types.cmti" {"mime_types.cmti"}
  "_build/install/default/lib/magic-mime/mime_types.mli" {"mime_types.mli"}
  "_build/install/default/lib/magic-mime/mime_types.ml" {"mime_types.ml"}
  "_build/install/default/lib/magic-mime/magic_mime_library.cma"
    {"magic_mime_library.cma"}
  "_build/install/default/lib/magic-mime/magic_mime_library.cmxa"
    {"magic_mime_library.cmxa"}
  "_build/install/default/lib/magic-mime/magic_mime_library.a"
    {"magic_mime_library.a"}
  "_build/install/default/lib/magic-mime/magic_mime_library.cmxs"
    {"magic_mime_library.cmxs"}
  "_build/install/default/lib/magic-mime/magic-mime.dune" {"magic-mime.dune"}
]
doc: [
  "_build/install/default/doc/magic-mime/README.md"
  "_build/install/default/doc/magic-mime/LICENSE.md"
  "_build/install/default/doc/magic-mime/CHANGES.md"
]
