lib: [
  "_build/install/default/lib/ppx_derivers/META" {"META"}
  "_build/install/default/lib/ppx_derivers/opam" {"opam"}
  "_build/install/default/lib/ppx_derivers/ppx_derivers.cmi"
    {"ppx_derivers.cmi"}
  "_build/install/default/lib/ppx_derivers/ppx_derivers.cmx"
    {"ppx_derivers.cmx"}
  "_build/install/default/lib/ppx_derivers/ppx_derivers.cmt"
    {"ppx_derivers.cmt"}
  "_build/install/default/lib/ppx_derivers/ppx_derivers.cmti"
    {"ppx_derivers.cmti"}
  "_build/install/default/lib/ppx_derivers/ppx_derivers.mli"
    {"ppx_derivers.mli"}
  "_build/install/default/lib/ppx_derivers/ppx_derivers.ml"
    {"ppx_derivers.ml"}
  "_build/install/default/lib/ppx_derivers/ppx_derivers.cma"
    {"ppx_derivers.cma"}
  "_build/install/default/lib/ppx_derivers/ppx_derivers.cmxa"
    {"ppx_derivers.cmxa"}
  "_build/install/default/lib/ppx_derivers/ppx_derivers.a" {"ppx_derivers.a"}
  "_build/install/default/lib/ppx_derivers/ppx_derivers.cmxs"
    {"ppx_derivers.cmxs"}
  "_build/install/default/lib/ppx_derivers/ppx_derivers.dune"
    {"ppx_derivers.dune"}
]
doc: "_build/install/default/doc/ppx_derivers/README.md"
