lib: [
  "_build/install/default/lib/yojson/META" {"META"}
  "_build/install/default/lib/yojson/opam" {"opam"}
  "_build/install/default/lib/yojson/yojson.cmi" {"yojson.cmi"}
  "_build/install/default/lib/yojson/yojson.cmx" {"yojson.cmx"}
  "_build/install/default/lib/yojson/yojson.cmt" {"yojson.cmt"}
  "_build/install/default/lib/yojson/yojson.cmti" {"yojson.cmti"}
  "_build/install/default/lib/yojson/yojson.mli" {"yojson.mli"}
  "_build/install/default/lib/yojson/yojson.ml" {"yojson.ml"}
  "_build/install/default/lib/yojson/yojson_biniou.cmi" {"yojson_biniou.cmi"}
  "_build/install/default/lib/yojson/yojson_biniou.cmx" {"yojson_biniou.cmx"}
  "_build/install/default/lib/yojson/yojson_biniou.cmt" {"yojson_biniou.cmt"}
  "_build/install/default/lib/yojson/yojson_biniou.cmti"
    {"yojson_biniou.cmti"}
  "_build/install/default/lib/yojson/yojson_biniou.mli" {"yojson_biniou.mli"}
  "_build/install/default/lib/yojson/yojson_biniou.ml" {"yojson_biniou.ml"}
  "_build/install/default/lib/yojson/yojson.cma" {"yojson.cma"}
  "_build/install/default/lib/yojson/yojson.cmxa" {"yojson.cmxa"}
  "_build/install/default/lib/yojson/yojson.a" {"yojson.a"}
  "_build/install/default/lib/yojson/yojson.cmxs" {"yojson.cmxs"}
  "_build/install/default/lib/yojson/yojson.dune" {"yojson.dune"}
]
bin: "_build/install/default/bin/ydump" {"ydump"}
doc: [
  "_build/install/default/doc/yojson/README.md"
  "_build/install/default/doc/yojson/LICENSE"
]
